#ifndef NGINZ_CONFIG_H
#define NGINZ_CONFIG_H

C_CAPSULE_START

#define MAX_POLL_FD 10000
#define NGINZ_INLINE inline
#define NGINZ_NUMBER_OF_PROCESSORS 5
//#define NGINZ_POLL_ALL_FLAGS POLLIN | POLLPRI | POLLHUP
#define NGINZ_POLL_ALL_FLAGS POLLIN
#define NGINZ_DEFAULT_PORT 9239
#define NGINZ_FACTORY_CREATE(obuff, psize, objsize, callback) ({OPP_PFACTORY_CREATE_FULL(obuff, psize, objsize, 1, OPPF_SWEEP_ON_UNREF, callback);})
#define NGINZ_HASHABLE_FACTORY_CREATE(obuff, psize, objsize, callback) ({OPP_PFACTORY_CREATE_FULL(obuff, psize, objsize, 1, OPPF_EXTENDED | OPPF_SWEEP_ON_UNREF, callback);})
#define NGINZ_SEARCHABLE_FACTORY_CREATE(obuff, psize, objsize, callback) ({OPP_PFACTORY_CREATE_FULL(obuff, psize, objsize, 1, OPPF_SEARCHABLE | OPPF_EXTENDED | OPPF_SWEEP_ON_UNREF, callback);})
#define NGINZ_MAX_USER_NAME_SIZE 32
#define NGINZ_MAX_ROOM_NAME_SIZE 32

C_CAPSULE_END

#endif // NGINZ_CONFIG_H
